### ISSUE TITLE
Where are the folders?

### ISSUE THREAD

**Issue by talyellin** [alexmackey/IntroToWebGLWithThreeJS#14]
After running npm install -g introtowebgl, my folder is empty.

Where are the folders? Every other nodeschool installation proceeds to download the content to the directory I'm installing from.

Thanks!

**Comment by z3t0** [comment]
You need to run introtowebgl

**Comment by talyellin** [comment]
Yes but after selecting the first item in the menu it returns text:

"## Sample code

In the assets folder you will find 3 other folders:" (etc)

**Comment by LOZORD** [comment]
Yeah, I agree that is is __not__ clear.

Here's what I did:

```bash
cd to/js-stuff/directory/or/whatever
mkdir intro-to-web-gl
cd intro-to-web-gl
npm install introtowebgl # notice no '-g' option
cd ./node_modules/introtowebgl
```

From there, you can run
```bash
vim assets/BoilerplateApp/scripts/app.js # editing the main file
open assets/BoilerplateApp/index.htm # view the results in your browser
```

Hope this helps!

**Comment by talyellin** [comment]
cd ./node_modules/introtowebgl did not work but "cd ../node_modules/introtowebgl" did.
