### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by s4chin** [alexmackey/IntroToWebGLWithThreeJS#17]
```sh
$ npm install -g introtowebgl
/home/s4chin/.npm-global/bin/introtowebgl -> /home/s4chin/.npm-global/lib/node_modules/introtowebgl/introtowebgl.js
/home/s4chin/.npm-global/lib
└─┬ introtowebgl@1.0.1 
  └── UNMET PEER DEPENDENCY stream-browserify@*

npm WARN bl@0.7.0 requires a peer of stream-browserify@* but none was installed.
$ npm -v
4.1.1
$ node -v
v6.9.4
```
Platform: Ubuntu 16.04
I have installed `browserify` globally if that's relevant. Please ask if additional info is required.

**Comment by z3t0** [comment]
have you tried `npm install stream-browserify`

**Comment by z3t0** [comment]
They're "required" by the code as different symbols so having browserify installed doesnt really help as far as I can tell from [here](https://www.npmjs.com/package/stream-browserify)

**Comment by s4chin** [comment]
It installs perfectly.
```
$ npm install -g stream-browserify
/home/s4chin/.npm-global/lib
└── stream-browserify@2.0.1 
```
`npm install -g introtowebgl` still gives the same error.

**Comment by z3t0** [comment]
https://github.com/affirmix/vinyl-map/pull/3/files This should fix the issue @alexmackey

**Comment by z3t0** [comment]
Also this seems to relate to #11

**Comment by s4chin** [comment]
@z3t0 Is there something I could do from my side to verify that it works?

**Comment by z3t0** [comment]
Seems to be working for me now, @s4chin try installing it again? Something changed, not sure what

**Comment by s4chin** [comment]
It didn't work for me even then. So I completely uninstalled node and npm and reinstalled it using nvm. Then it got installed. :+1:
