### ISSUE TITLE
In #5 : Loading :: formatting strange

### ISSUE THREAD

**Issue by mdda** [alexmackey/IntroToWebGLWithThreeJS#3]
There are a couple of bad charset quotes, and what appears to be weird indentation in the instructions that should be (IMHO) : 

```
var loader = new THREE.JSONLoader(),
             mesh;

var goose_path = 'file:///FULL-LOCAL-PATH/assets/BoilerplateApp/scripts/GooseModel/';
loader.load(goose_path+'gooseFull.js', function (geometry) {
  var gooseMaterial = new THREE.MeshLambertMaterial({
    map: THREE.ImageUtils.loadTexture(goose_path+'goose.jpg')
  });

  mesh = new THREE.Mesh(geometry, gooseMaterial);
  mesh.scale.set(1000, 1000, 1000);

  scene.add(mesh);
});
```

Is there also an argument for putting the `mesh` declaration in the overall `var`, so that we can manipulate it in `render()`?  Or is the preferred way to name the mesh, etc?

Would you prefer a patch?

**Comment by rk08** [comment]
@mdda do u have solution for second exercise

**Comment by mdda** [comment]
@rk08 - Yes, I have "solutions" for all the exercises (though, they're not formally "question solved" since many of the exercises are really invitations to play around with the excellent ThreeJS).

However, I don't see how to tell you about my solution to number 2 without it being a potential spoiler for others...
