### ISSUE TITLE
Exercise talking about asset folder but doesn't tell, where to find it.

### ISSUE THREAD

**Issue by sudodoki** [alexmackey/IntroToWebGLWithThreeJS#5]
If you follow the instruction of installing introtowebgl globally there might be a case when you're running `introtowebgl` and read about asset folder but got no idea, where to get those.
I'm no expert, but can suggest next several solutions and will proceed with one of them if you find fit. 
1) use folder of file executed or read symlink value to provide exact location of introtowebgl package path & incorporate that to the help text output.
2) add 'introtowebgl bootstrap' or similar command that would copy `assets` to current working directory.

Maybe, someone can come with other solutions for this.

**Comment by sudodoki** [comment]
Just in case someone is wondering what to do in this situation I might suggest one of the options
1) cloning this repo locally `git clone git@github.com:alexmackey/IntroToWebGLWithThreeJS.git` & working with asset folder
2) install it locally, by running `mkdir myexercise && cd myexercise && npm init --yes && npm i --save introtowebgl` and then you can find the contents of the introtowebgl package in node_modules folder
3) install introtowebgl globally as suggested by instruction on the site, and then
on Linux run 
```
readlink -f `which introtowebgl`
``` which should get you the absolute path to the package and you just traverse that
or on Mac run
```
ls -la `which introtowebgl`
```
To get the link address and relative path to the original files we're interested in - you can figure absolute path by your own, or use some ready made solution from [this so question](http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac).

**Comment by alexmackey** [comment]
@sudodoki Ah good point - ill add some more detail around this to the intro. As the workshop could run on different environments im not sure symlinks/batch files would work so well.
