### ISSUE TITLE
completed my exercise

### ISSUE THREAD

**Issue by rk08** [alexmackey/IntroToWebGLWithThreeJS#7]
Hi,

Whenever I run this piece of code in my files it shows i have completed my exercise.
Can you guys tell me why its happening

var exercise      = require('workshopper-exercise')()

module.exports = exercise

**Comment by sudodoki** [comment]
Oh, in the intro it states that there's no verification.
https://github.com/alexmackey/IntroToWebGLWithThreeJS/blob/master/exercises/01_Introduction/problem.md#no-verification

**Comment by rk08** [comment]
@sudodoki can you enable verification step

**Comment by alexmackey** [comment]
The questions/exercises are built on the workshopper framework which is setup with a verification step. This makes a lot of sense with items such as node and git workshops where it is easy to verify if the user has completed the task successfully. 
However its pretty tricky with WebGL/three.js to verify if the user has completed the task successfully as there are so many different ways you could complete a task.

**Comment by rk08** [comment]
@alexmackey atleast you can provide solutions for each task...
