### ISSUE TITLE
animations

### ISSUE THREAD

**Issue by allenjd3** [alexmackey/IntroToWebGLWithThreeJS#9]
Alright, lets be honest, I'm probably just an idiot but when 03 Manipulate Objects says to create an animation that rotates and resizes the cube, I don't even know where to begin. I tried to wrap the camera.position.set( 0, 0, 100 ); in a for loop but that just gave a bunch of errors.  Is there a built in function that does the moving?

Thanks,
Jim

**Comment by alexmackey** [comment]
Hey @allenjd3 dont worry I spent many hours scratching my head with various three.js issues. 

Check out my examples from my three.js Pluralsight course - there is one that rotates the cube here: 

https://github.com/alexmackey/threeJsBasicExamples/blob/master/Module2_ThreeJsBuildingBlocks/Demo01%20-%20hello%20world/scripts/app.js
